name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: make clean
      run: make clean
    - name: make fclean
      run: make fclean
    - name: make re
      run: make re
